### ISSUE TITLE
else seems redundant here

### ISSUE THREAD

**Issue by AlexKap23** [al-fashola/TicTacToe#2]
https://github.com/al-fashola/TicTacToe/blob/d5c1bafddf6c795906a6fc1f6c9fbd5d56635396/TicTacToe/Logic.cs#L44

since you are returning inside your if case, you don't have to actually have an else case. cause if the if is false it will go immediately after it and execute the rest of the code. Right now there's no other code so you can immediately have your return false. 

A even cleaner solution would be to return the resulf of the check that you have in your if case immediately, since if this is true you are returning true. 

that will make the code much cleaner, less complex and easier to read also.

**Comment by al-fashola** [comment]
fixed in [e347819]
