### ISSUE TITLE
replace empty char with a constant

### ISSUE THREAD

**Issue by AlexKap23** [al-fashola/TicTacToe#3]
https://github.com/al-fashola/TicTacToe/blob/d5c1bafddf6c795906a6fc1f6c9fbd5d56635396/TicTacToe/Logic.cs#L39

you are using ' ' multiple times on your code. in general hardcoded strings/chars of that kind should be avoided in the code. You can declare a constant and use that instead. Also, you can create a new file called Constants, and move all your constants in that.

**Comment by al-fashola** [comment]
Resolved in 
6b1a33d
